show how to connect to remote endpoints
elastic/powershell pull request #1
Opened 2019-09-27 02:50 UTC by geekpete

2019-09-27 03:52 UTC, russcam requested changes
Suggested a couple of changes

2019-09-27 03:52 UTC, russcam commented on Elastic.Console/README.md
> +The default endpoint is `http://localhost:9200` but to connect to a specific endpoint use the `-Uri` parameter:
```suggestion
The default endpoint is `http://localhost:9200` but you can connect to any host and port
```

2019-09-27 03:52 UTC, russcam commented on Elastic.Console/README.md
> +es -Uri http://192.168.0.1:9200 _cat/indices
```suggestion
es https://example.com:9200/_cat/indices
```

2019-09-27 04:48 UTC, geekpete commented
No probs, I've added those changes.

2019-09-27 05:17 UTC, russcam commented
Thanks @geekpete. Just looking at where this is in the README, it might be better to put it after the line

```
Sends a request to Elasticsearch to list the indices in the cluster. es is an alias for Invoke-Elasticsearch
```

and before the PUT document example, because the following line is the description for the PUT doc example.

2019-09-30 04:36 UTC, russcam approved these changes
LGTM. Thanks @geekpete 👍

2019-09-30 04:36 UTC, geekpete commented
Thanks! Merge away :)

2019-09-30 04:37 UTC, merged